steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/bingo-322514/bingo-dev", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/bingo-322514/bingo-dev"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "bingo-dev",
        "--image",
        "gcr.io/bingo-322514/bingo-dev",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
images:
  - "gcr.io/bingo-322514/bingo-dev"
options:
  logging: CLOUD_LOGGING_ONLY
  # TODO: Solicitar confirmacion de build y deploy de una nueva version.
  # TODO: Enviar correo donde se informa la actualizacion.
  # TODO: Notificar que el envio fallo.
  # TODO: Deploy functions.
  # TODO: Deploy hosting [front / back].
  # TODO: Format all files "npx prettier --write ."
  # TODO: Add tests
  # TODO: Clonar el storage de dev a prod.
